import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";

export const maxDuration = 30;

// Parse a CSV string into rows. Handles quoted fields with commas inside.
function parseCSV(text: string): { headers: string[]; rows: Record<string, string>[] } {
  const lines = text.trim().split(/\r?\n/);
  if (lines.length < 2) return { headers: [], rows: [] };

  function splitLine(line: string): string[] {
    const cols: string[] = [];
    let cur = "";
    let inQ  = false;
    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (c === '"') { inQ = !inQ; continue; }
      if (c === "," && !inQ) { cols.push(cur.trim()); cur = ""; continue; }
      cur += c;
    }
    cols.push(cur.trim());
    return cols;
  }

  const headers = splitLine(lines[0]).map(h => h.toLowerCase().trim());
  const rows = lines.slice(1).filter(l => l.trim()).map(l => {
    const vals = splitLine(l);
    return Object.fromEntries(headers.map((h, i) => [h, vals[i] ?? ""]));
  });
  return { headers, rows };
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json() as { orderId: string; csvText: string };
    const { orderId, csvText } = body;

    if (!orderId || !csvText) {
      return NextResponse.json({ error: "Missing orderId or csvText" }, { status: 400 });
    }

    // Verify order exists
    const { data: order, error: orderErr } = await supabase
      .from("orders")
      .select("id, email, business_name, customer_name")
      .eq("id", orderId)
      .single();

    if (orderErr || !order) {
      return NextResponse.json({ error: "Order not found" }, { status: 404 });
    }

    const { headers, rows } = parseCSV(csvText);

    // Auto-detect name and email columns
    const nameCol  = headers.find(h => /\bname\b/i.test(h)) ?? headers[0];
    const emailCol = headers.find(h => /\bemail\b/i.test(h));

    if (!emailCol) {
      return NextResponse.json({ error: "Could not find an email column. Make sure your CSV has a column with 'email' in the header." }, { status: 400 });
    }

    const validRows = rows.filter(r => r[emailCol]?.includes("@"));
    if (validRows.length === 0) {
      return NextResponse.json({ error: "No valid email addresses found in CSV." }, { status: 400 });
    }

    // Delete existing unsent contacts for this order
    await supabase
      .from("survey_contacts")
      .delete()
      .eq("order_id", orderId)
      .is("sent_at", null);

    // Insert new contacts — tokens are generated by Supabase default
    const inserts = validRows.map(r => ({
      order_id: orderId,
      name:     r[nameCol] ?? null,
      email:    r[emailCol],
    }));

    const { data: contacts, error: insertErr } = await supabase
      .from("survey_contacts")
      .insert(inserts)
      .select("id, name, email, token");

    if (insertErr) {
      console.error("Insert contacts error:", insertErr);
      return NextResponse.json({ error: "Failed to save contacts" }, { status: 500 });
    }

    return NextResponse.json({ contacts, count: contacts?.length ?? 0 });
  } catch (err) {
    console.error("Upload contacts error:", err);
    return NextResponse.json({ error: "Upload failed" }, { status: 500 });
  }
}
